// ════════════════════════════════════════════════════════════════════════════
// GENERATED by tools/build-erp-core.js from index.html — do not edit by hand.
// ════════════════════════════════════════════════════════════════════════════
// The app's own Priority import, copied verbatim so a batch from Engini lands
// exactly as the same rows would from a Priority Excel file. To change how
// Priority data is read, change index.html and re-run the script.

// What the browser has and the server does not. Every row the function writes
// carries its company explicitly, so rowCid never falls back to this.
const DEFAULT_COMPANY_ID="00000000-0000-0000-0000-000000000001";
let _companyId=null;
const rowCid=x=>(x&&x.companyId)||_companyId;
const deptBranches=d=>sortBranches((d&&d.branches)||[]);

// ── from index.html: branches ────────────────────────────────────────────────────
const BRANCHES=[
  {code:"51",name:"אזרחי",color:"#3b82f6"},
  {code:"52",name:"משולבות",color:"#a78bfa"},
  {code:"53",name:'תק"ש',color:"#10b981"},
  {code:"57",name:"מעבדות",color:"#f59e0b"}
];
const BRANCH_MAP=new Map(BRANCHES.map(b=>[b.code,b]));
// Priority writes a literal 0 for "no branch", exactly as it does for the project code.
const branchCode=v=>{const c=String(v==null?"":v).trim();return(c==="0"||c==="-")?"":c};
const branchName=c=>BRANCH_MAP.get(branchCode(c))?.name||"";
const branchColor=c=>BRANCH_MAP.get(branchCode(c))?.color||"#8b95a8";
// "53 · תק\"ש" for a known number, "סניף 60" for one the catalogue has never seen.
const branchLabel=c=>{const k=branchCode(c);if(!k)return"";const n=branchName(k);return n?`${k} · ${n}`:`סניף ${k}`};
// Every branch number the app currently knows: the catalogue, whatever the ERP
// actually sent, and whatever a department was given. Sorted numerically, so
// 51 · 52 · 53 · 57 read in order and a non-numeric code lands at the end.
const sortBranches=list=>[...new Set((list||[]).map(branchCode).filter(Boolean))]
  .sort((a,b)=>{const na=Number(a),nb=Number(b);
    return(isFinite(na)&&isFinite(nb))?na-nb:String(a).localeCompare(String(b),"he",{numeric:true})});

// ── from index.html: dates ───────────────────────────────────────────────────────
function isoDay(v){
  const m=/^(\d{4})-(\d{2})-(\d{2})/.exec(String(v==null?"":v).trim());
  if(!m)return "";
  const y=Number(m[1]),mo=Number(m[2]),d=Number(m[3]);
  const leap=(y%4===0&&y%100!==0)||y%400===0;
  const days=[31,leap?29:28,31,30,31,30,31,31,30,31,30,31][mo-1];
  return(y>=1&&days&&d>=1&&d<=days)?`${m[1]}-${m[2]}-${m[3]}`:"";
}

// ── from index.html: dates ───────────────────────────────────────────────────────
const isoOf=d=>{const t=new Date(d);return new Date(t.getTime()-t.getTimezoneOffset()*6e4).toISOString().slice(0,10)};

// ── from index.html: DB row converters ───────────────────────────────────────────
// ── DB row converters (DB → App format) ────────────────────────────────────
// No password travels with a user record any more: it lives encrypted on the
// server, and an admin's screen asks for it on demand (revealUserPasswords).
const dbToUser=r=>({id:r.id,username:r.username,role:r.role,name:r.name,
  projectAccess:r.project_access,stageAccess:r.stage_access,
  branchAccess:r.branch_access==="all"?"all":(Array.isArray(r.branch_access)?r.branch_access.map(branchCode).filter(Boolean):[]),
  branchNone:r.branch_none===true,
  canEdit:r.can_edit,canView:r.can_view,active:r.active,hourlyRate:r.hourly_rate,saleRate:r.sale_rate||0,
  departmentId:r.department_id||"",managerId:r.manager_id||"",
  companyId:r.company_id||_companyId||DEFAULT_COMPANY_ID,loginAttempts:r.login_attempts||0,lockedUntil:r.locked_until,lastLogin:r.last_login});
const userToDb=u=>({id:u.id,username:u.username,
  role:u.role,name:u.name,project_access:u.projectAccess,stage_access:u.stageAccess,
  branch_access:u.branchAccess==="all"?"all":sortBranches(Array.isArray(u.branchAccess)?u.branchAccess:[]),
  branch_none:u.branchNone===true,
  can_edit:u.canEdit,can_view:u.canView,active:u.active!==false,hourly_rate:Number(u.hourlyRate||0),sale_rate:Number(u.saleRate||0),
  department_id:u.departmentId||null,manager_id:u.managerId||null,
  company_id:rowCid(u)});
const dbToOrder=r=>({id:r.id,woNumber:r.wo_number,pn:r.pn,description:r.description,qty:r.qty,
  unitPrice:r.unit_price,projectId:r.project_id,branch:branchCode(r.branch),receivedDate:r.received_date,targetDate:r.target_date,
  stageIds:r.stage_ids,blockId:r.block_id,serials:r.serials,shortages:r.shortages,
  defects:r.defects,deliveredSerials:r.delivered_serials,status:r.status,
  // What the ERP actually wrote in סטטוס פק"ע, kept verbatim beside the four
  // statuses it folds onto — it is the only place the reason a פק"ע is stuck
  // ("בעית ח\"ג חסר", "הוקפאה") survives the import.
  erpStatus:r.erp_status||"",erpNote:r.erp_note||"",
  companyId:r.company_id||_companyId||DEFAULT_COMPANY_ID});
const orderToDb=o=>({id:o.id,wo_number:o.woNumber,pn:o.pn||null,description:o.description||null,
  qty:Number(o.qty)||0,unit_price:Number(o.unitPrice)||0,project_id:o.projectId||null,
  branch:branchCode(o.branch)||null,
  received_date:isoDay(o.receivedDate)||null,target_date:isoDay(o.targetDate)||null,stage_ids:o.stageIds||[],
  block_id:o.blockId||null,serials:o.serials||[],shortages:o.shortages||[],
  defects:o.defects||[],delivered_serials:o.deliveredSerials||[],status:o.status||"open",
  erp_status:o.erpStatus||null,erp_note:o.erpNote||null,
  company_id:rowCid(o),updated_at:new Date().toISOString()});
const dbToLog=r=>({id:r.id,userId:r.user_id,userName:r.user_name,serialId:r.serial_id,
  serialSn:r.serial_sn,stageId:r.stage_id,orderId:r.order_id,startTime:r.start_time,
  endTime:r.end_time,completed:r.completed,durationMin:r.duration_min,paused:r.paused,
  pauseStart:r.pause_start,totalPauseMin:r.total_pause_min,pauseLog:r.pause_log,
  bulk:r.bulk,bulkGroupId:r.bulk_group_id,bulkCount:r.bulk_count,
  holdInfo:(r.hold_info&&typeof r.hold_info==="object")?r.hold_info:null,
  companyId:r.company_id||_companyId||DEFAULT_COMPANY_ID});
const logToDb=w=>({id:w.id,user_id:w.userId,user_name:w.userName,serial_id:w.serialId||null,
  serial_sn:w.serialSn||null,stage_id:w.stageId||null,order_id:w.orderId||null,
  start_time:w.startTime||null,end_time:w.endTime||null,completed:w.completed||false,
  duration_min:Number(w.durationMin||0),paused:w.paused||false,pause_start:w.pauseStart||null,
  total_pause_min:Number(w.totalPauseMin||0),pause_log:w.pauseLog||[],
  bulk:w.bulk||false,bulk_group_id:w.bulkGroupId||null,bulk_count:w.bulkCount||null,
  hold_info:w.holdInfo||null,
  company_id:rowCid(w)});
const dbToTask=r=>({id:r.id,userId:r.user_id,userName:r.user_name,name:r.name,
  description:r.description,price:r.price,active:r.active,completed:r.completed,partial:r.partial,
  startTime:r.start_time,endTime:r.end_time,durationMin:r.duration_min,paused:r.paused,
  pauseStart:r.pause_start,totalPauseMin:r.total_pause_min,pauseLog:r.pause_log,
  createdAt:r.created_at,companyId:r.company_id||_companyId||DEFAULT_COMPANY_ID});
const taskToDb=t=>({id:t.id,user_id:t.userId,user_name:t.userName,name:t.name,
  description:t.description||null,price:Number(t.price||0),active:t.active||false,
  completed:t.completed||false,partial:t.partial||false,start_time:t.startTime||null,
  end_time:t.endTime||null,duration_min:Number(t.durationMin||0),paused:t.paused||false,
  pause_start:t.pauseStart||null,total_pause_min:Number(t.totalPauseMin||0),
  pause_log:t.pauseLog||[],company_id:rowCid(t),updated_at:new Date().toISOString()});
const dbToStage=r=>({id:r.id,name:r.name,order:r.stage_order,color:r.color,price:r.price,hourlyRate:r.hourly_rate||0,roleId:r.role_id||"",minutes:Number(r.minutes||0),companyId:r.company_id||_companyId||DEFAULT_COMPANY_ID});
const stageToDb=s=>({id:s.id,name:s.name,stage_order:s.order||0,color:s.color||"#3b82f6",price:Number(s.price||0),hourly_rate:Number(s.hourlyRate||0),role_id:s.roleId||null,minutes:Number(s.minutes||0),company_id:rowCid(s)});
const dbToBlock=r=>({id:r.id,name:r.name,stages:r.stages,companyId:r.company_id||_companyId||DEFAULT_COMPANY_ID});
const blockToDb=b=>({id:b.id,name:b.name,stages:b.stages||[],company_id:rowCid(b)});
const dbToProject=r=>({id:r.id,name:r.name,companyId:r.company_id||_companyId||DEFAULT_COMPANY_ID});
const projectToDb=p=>({id:p.id,name:p.name,company_id:rowCid(p)});
const dbToDept=r=>({id:r.id,name:r.name,color:r.color||"#3b82f6",managerId:r.manager_id||"",
  branches:Array.isArray(r.branch_codes)?r.branch_codes.map(branchCode).filter(Boolean):[],
  companyId:r.company_id||_companyId||DEFAULT_COMPANY_ID});
const deptToDb=d=>({id:d.id,name:d.name,color:d.color||"#3b82f6",manager_id:d.managerId||null,
  branch_codes:deptBranches(d),company_id:rowCid(d)});
// Daily work plans — a manager assigns a worker an order+stage to work on for a given day.
const dbToPlan=r=>({id:r.id,userId:r.user_id,userName:r.user_name,date:r.plan_date,orderId:r.order_id||"",stageId:r.stage_id||"",targetQty:Number(r.target_qty||0),serialIds:Array.isArray(r.serial_ids)?r.serial_ids:[],note:r.note||"",done:r.done||false,createdBy:r.created_by||"",createdByName:r.created_by_name||"",createdAt:r.created_at,companyId:r.company_id||_companyId||DEFAULT_COMPANY_ID});
const planToDb=p=>({id:p.id,user_id:p.userId,user_name:p.userName||null,plan_date:p.date,order_id:p.orderId||null,stage_id:p.stageId||null,target_qty:Number(p.targetQty||0),serial_ids:Array.isArray(p.serialIds)?p.serialIds:[],note:p.note||null,done:p.done||false,created_by:p.createdBy||null,created_by_name:p.createdByName||null,company_id:rowCid(p),updated_at:new Date().toISOString()});
// זמן תקן — the target minutes defined up-front for a מק"ט, stage by stage.
// Independent of what the floor actually measures (זמן בפועל, from the work logs)
// and of what the price list sells (זמן מכירה).
const dbToPnStd=r=>({id:r.id,pn:r.pn||"",stageMin:(r.stage_minutes&&typeof r.stage_minutes==="object")?r.stage_minutes:{},
  total:Number(r.total_min||0),note:r.note||"",updatedBy:r.updated_by||"",updatedAt:r.updated_at||"",companyId:r.company_id||_companyId||DEFAULT_COMPANY_ID});
const pnStdToDb=p=>({id:p.id,pn:p.pn||"",stage_minutes:p.stageMin||{},total_min:Number(p.total||0),
  note:p.note||null,updated_by:p.updatedBy||null,company_id:rowCid(p),updated_at:new Date().toISOString()});

// ── from index.html: statuses ────────────────────────────────────────────────────
const SL={open:"פתוחה",partial:"חלקית",complete:"הושלמה",blocked:"תקועה"};

// ── from index.html: palette ─────────────────────────────────────────────────────
const COLORS=["#3b82f6","#10b981","#8b5cf6","#f59e0b","#ef4444","#06b6d4","#f97316","#ec4899","#84cc16","#a78bfa"];

// ── from index.html: ids and clocks ──────────────────────────────────────────────
const uid=()=>Math.random().toString(36).slice(2,9);
const todays=()=>new Date().toISOString().slice(0,10);
const nowISO=()=>new Date().toISOString();

// ── from index.html: progress records ────────────────────────────────────────────
const isQtyLog=w=>!!w&&!!w.completed&&!w.serialId&&!!w.orderId&&!!w.stageId&&Number(w.bulkCount)>0;

// ── from index.html: standard times ──────────────────────────────────────────────
const pnKey=pn=>String(pn||"").trim();
// Two devices can each create a record for the same מק"ט before they sync, so the
// newest edit wins rather than whichever row happened to load last.
function pnStdIndex(pnStandards){
  const m=new Map();
  (pnStandards||[]).forEach(r=>{
    const k=pnKey(r.pn);if(!k)return;
    const cur=m.get(k);
    if(!cur||String(r.updatedAt||"")>=String(cur.updatedAt||""))m.set(k,r);
  });
  return m;
}

// ── from index.html: spreadsheet cells ───────────────────────────────────────────
const xlNorm=s=>String(s==null?"":s).replace(/['"׳״‘’“”]/g,"").replace(/\s+/g," ").trim().toLowerCase();
const xlRow=r=>{const o={};Object.keys(r).forEach(k=>{o[xlNorm(k)]=r[k]});return o};
const xlGet=(r,...keys)=>{for(const k of keys){const v=r[xlNorm(k)];if(v!==undefined&&v!==null&&String(v).trim()!=="")return v}return""};
// ── Reading a number out of a spreadsheet cell ────────────────────────────
// This was `Number(String(v).replace(/[^\d.\-]/g,""))` — keep the digits, drop
// everything else. That is fine for "1,234 ₪" and catastrophic for a cell that is
// not a number at all, because scraping digits always yields *a* number.
//
// The workbook is read with cellDates:true, so a column Excel has a date format on
// arrives as a JS Date — and a date format left on a price column is an ordinary
// spreadsheet accident. String(date) is
// "Tue Jan 09 1900 09:36:00 GMT+0220 (Israel Standard Time)", whose digits scrape
// to 919000936000220: day, year, time, UTC offset, run together. Ninety פק"ע came
// in priced like that, and the dashboard multiplied each by the units that had
// finished — הכנסה ממומשת read ₪1,604,276,474,982,000 next to a ₪706,388 forecast.
//
// So a Date is converted back to the serial the cell actually holds, a number is
// taken as it is, and a string has to still *look* like a number once the currency
// symbols, spaces, direction marks and thousands separators come off. Anything
// else is 0 — which is what the app already means by "no value".
const XL_EPOCH=Date.UTC(1899,11,30);
const xlSerialOf=d=>{
  const days=(d.getTime()-d.getTimezoneOffset()*6e4-XL_EPOCH)/864e5;
  // Historic offsets are not whole minutes (Jerusalem ran at +02:20:40 until 1918)
  // and getTimezoneOffset rounds to one, so a whole-day serial can come back as
  // 27.0005. Anything within a minute of a whole day is that whole day.
  return Math.abs(days-Math.round(days))<1/1440?Math.round(days):Math.round(days*1e4)/1e4;
};
// `instanceof Date` is per-realm and a workbook parsed inside a worker or an
// iframe hands back a Date built in that realm — where it answers false, and the
// value falls through to be read as a string, which is the whole bug again.
const isDate=v=>Object.prototype.toString.call(v)==="[object Date]";
function xlNum(v){
  if(v==null||v==="")return 0;
  if(isDate(v))return isNaN(v.getTime())?0:xlSerialOf(v);
  if(typeof v==="number")return isFinite(v)?v:0;
  if(typeof v==="boolean")return v?1:0;
  let s=String(v).trim()
    .replace(/[\u200e\u200f\u202a-\u202e\u00a0]/g,"")   // direction marks, nbsp — as escapes: invisible in source
    .replace(/[₪$€£]/g,"")
    .replace(/\s/g,"");
  if(!s)return 0;
  // Accounting negatives: (1,234) and a trailing minus both mean -1234.
  let neg=false;
  const paren=s.match(/^\((.*)\)$/);
  if(paren){neg=true;s=paren[1]}
  if(s.startsWith("-")){neg=!neg;s=s.slice(1)}
  else if(s.endsWith("-")){neg=!neg;s=s.slice(0,-1)}
  // Thousands separators, either convention: 1,234.56 and 1.234,56 are the same
  // number, and the *last* separator present says which one is the decimal point.
  const lastC=s.lastIndexOf(","),lastD=s.lastIndexOf(".");
  if(lastC>-1&&lastD>-1)s=lastC>lastD?s.replace(/\./g,"").replace(",","."):s.replace(/,/g,"");
  else if(lastC>-1)s=/^\d{1,3}(,\d{3})+$/.test(s)?s.replace(/,/g,""):s.replace(",",".");
  else if(/^\d{1,3}(\.\d{3})+$/.test(s))s=s.replace(/\./g,"");
  // What is left has to be the whole value — no letters, no second separator, and
  // nothing scraped out of the middle of a word.
  if(!/^(\d+(\.\d*)?|\.\d+)$/.test(s))return 0;
  const n=Number(s);
  if(!isFinite(n))return 0;
  return neg?-n:n;
}
const xlBool=v=>/^(כן|נמסר|התקבל|בוצע|yes|y|true|1|v|✓)$/i.test(String(v==null?"":v).trim());
// Every answer xlDate gives passes through here: a real calendar day after 1900,
// or nothing. The text branches used to hand back whatever digits they matched,
// and an empty date cell that Excel had already formatted arrives as the text
// "1900-01-00" (or "00/01/1900") — serial 0, a day that does not exist. That
// went straight into received_date / target_date, and the database refused the
// whole save over it. Nothing before 1901 is a date anyone typed, which is the
// rule the Date branch below already applied.
const xlDay=s=>{const d=isoDay(s);return d>"1901"?d:""};
function xlDate(v){
  if(v==null||v==="")return"";
  // An empty date cell in an ERP export often arrives as a time-only value,
  // which is Excel serial 0 — the last day of 1899, not a real date.
  if(isDate(v))return isNaN(v.getTime())?"":xlDay(isoOf(v));
  // Priority writes "no date" as a plain 0, and a bare "0" would otherwise be
  // parsed by Date() as the year 2000 — anything non-positive is simply empty.
  if(typeof v==="number")return(isFinite(v)&&v>0)?xlDay(new Date(Date.UTC(1899,11,30)+Math.round(v)*864e5).toISOString()):"";
  const s=String(v).trim();
  // A date column that arrived as text still holds an Excel serial (roughly 1900-2064)
  if(/^-?\d+(\.\d+)?$/.test(s)){const n=Number(s);return(n>0&&n<60000)?xlDay(new Date(Date.UTC(1899,11,30)+Math.round(n)*864e5).toISOString()):""}
  let m=s.match(/^(\d{4})[-/.](\d{1,2})[-/.](\d{1,2})/);
  if(m)return xlDay(`${m[1]}-${String(m[2]).padStart(2,"0")}-${String(m[3]).padStart(2,"0")}`);
  m=s.match(/^(\d{1,2})[-/.](\d{1,2})[-/.](\d{2,4})/);
  if(m){let y=Number(m[3]);if(y<100)y+=2000;return xlDay(`${y}-${String(m[2]).padStart(2,"0")}-${String(m[1]).padStart(2,"0")}`)}
  const d=new Date(s);return isNaN(d)?"":xlDay(isoOf(d));
}

// ── from index.html: Priority import ─────────────────────────────────────────────
const PRI_H={wo:'מספר פק"ע',pn:'מק"ט',desc:'תיאור מוצר',branch:'סניף',project:'פרויקט',qty:'כמות',
  price:"מחיר אלת'א בש'ח",release:'תאריך שחרור',endDate:'ת. סיום יצור',
  // Priority spelled this header שלה before it was corrected to שלב; both are read.
  seq:'שלב בפק"ע',seqAlt:'שלה בפק"ע',op:'פעולה',
  opDesc:'תאור פעולה',wc:'מרכז עבודה',reported:'כמות מדווחת',remain:'יתרה לבצוע',
  stdPn:"ז.תקן ליח' בדק' למקט",stdWo:"ז.תקן ליח' בדק' בפקע",status:'סטטוס פק"ע'};
// A free-text reason beside the status — not every Priority report carries one,
// and the header it carries it under differs between reports, so every spelling
// seen so far is tried. Whatever it holds is shown on a stuck פק"ע next to the
// status that stopped it.
const PRI_NOTE_H=["סיבת עיכוב","סיבת העיכוב","סיבת תקיעה","סיבת התקיעה","סיבה","סיבת עצירה",
  "הערת סטטוס",'הערות פק"ע',"הערות","הערה","פירוט","תיאור סטטוס","status note","remark","remarks"];
// ── סטטוס פק"ע של Priority — המילון המלא ──────────────────────────────────
// Every value Priority's סטטוס פק"ע column carries, written out in full: what it
// actually means on the floor, which of the app's four statuses it folds onto,
// and — the part those four cannot say — where the פק"ע stands relative to the
// production line itself.
//
// The phase is the distinction a floor manager asks for first and the status
// hides: "פתוחה" and "שוחררה" are both open, and both mean nobody has touched
// the work — the פק"ע is on paper, not on the line. Lumping them together with
// "הועבר לייצור" (also open, but already in the queue) made the open pile
// unreadable, so the phase is carried beside the status and filtered on its own.
//
//   pre        תהליך הייצור לא התחיל — פתוחה או שוחררה, ותו לא
//   line       בתהליך ייצור, מהדפסת התיק ועד ההמתנה לאריזה
//   stuck      בתהליך, אבל נעצרה מסיבה מזוהה; הסטטוס עצמו הוא הסיבה
//   done       הסתיימה — דווח אחרון, נסגרה, COC
//   cancelled  מבוטלת — ״לא להציג״: מדולגת בייבוא ומוסתרת במסכים
const ST_PHASE={
  pre:{key:"pre",label:"טרם התחיל ייצור",icon:"🚧",color:"#f59e0b",
    hint:'הפק"ע נפתחה או שוחררה ב-ERP ותהליך הייצור עוד לא התחיל. אין עליה עבודה לדווח, והיא לא אמורה להיספר כ"בתהליך".'},
  line:{key:"line",label:"בתהליך ייצור",icon:"🏭",color:"#3b82f6",
    hint:'תהליך הייצור של הפק"ע התחיל — מהכנת התיק והליקוט ועד הביקורת והאריזה. גם המתנה לתחנה הבאה היא חלק מהתהליך.'},
  stuck:{key:"stuck",label:"עצורה",icon:"⛔",color:"#ef4444",
    hint:'הפק"ע בתהליך ייצור אבל נעצרה מסיבה מזוהה — חוסר, בעיה הנדסית או המתנה. הסטטוס מה-ERP הוא סיבת התקיעה.'},
  done:{key:"done",label:"הסתיימה",icon:"✅",color:"#10b981",
    hint:'הפק"ע סיימה את התהליך — דווח אחרון, נסגרה או קיבלה COC. לא צפויה עליה עוד עבודה.'},
  cancelled:{key:"cancelled",label:"מבוטלת",icon:"🚫",color:"#8b95a8",
    hint:'הפק"ע בוטלה ולא תיוצר. לפי הגדרת התהליך היא לא מוצגת — לא ברשימות, לא בדשבורד ולא באיחורים — אלא אם בוחרים במפורש להציג אותה. בייבוא היא מדולגת כברירת מחדל.'}
};
const PHASE_ORDER=["pre","line","stuck","done","cancelled"];
// status text (as Priority writes it) → {st: app status, phase, official, desc}
// `official` marks the twenty values that came over on the אנה status list. The
// rest are values seen in earlier exports and kept as a safety net — they are
// placed by the same rules, and the dictionary says they are not on the list, so
// nobody reads an inference as a decision.
const PRI_STATUS_INFO={
  // ── טרם התחיל תהליך ייצור ───────────────────────────────────────────────
  "פתוחה":{st:"open",phase:"pre",official:true,
    desc:'הפק"ע נפתחה ב-ERP ותהליך הייצור לא התחיל. אין הקצאת חומרים פעילה ואין מה לדווח עליה.'},
  "שוחררה":{st:"open",phase:"pre",official:true,
    desc:'הפק"ע שוחררה לייצור והחומרים הוקצו — אבל תהליך הייצור עדיין לא התחיל. היא ממתינה בתור.'},
  // ── בתהליך ייצור ────────────────────────────────────────────────────────
  "הודפסה":{st:"partial",phase:"line",official:true,
    desc:'תיק העבודה של הפק"ע הודפס — התהליך התחיל בהכנת התיק לרצפה.'},
  "קדם יצור":{st:"partial",phase:"line",official:true,
    desc:'שלב ההכנה שלפני העבודה עצמה: תיק, חומרים, כלים ותוכניות.'},
  "ממתין ליצור":{st:"partial",phase:"line",official:true,
    desc:'כל התנאים מולאו והפק"ע ממתינה בתור לתחנה. זמן המתנה בתוך התהליך, לא זמן עבודה.'},
  "הועבר לייצור":{st:"partial",phase:"line",official:true,
    desc:'הפק"ע הועברה רשמית לרצפת הייצור ונמצאת בתור של הקו.'},
  "מאושרת לקיוט":{st:"partial",phase:"line",official:true,
    desc:'הפק"ע אושרה לליקוט ערכת החומרים (Kitting).'},
  "בתהליך קיוט":{st:"partial",phase:"line",official:true,
    desc:'ערכת החומרים של הפק"ע מלוקטת כעת במחסן.'},
  "בתהליך ייצור":{st:"partial",phase:"line",official:true,
    desc:'העבודה על הפק"ע רצה בפועל — דווחו עליה פעולות ייצור.'},
  "בקרת יצור":{st:"partial",phase:"line",official:true,
    desc:'בקרת ייצור — התאמת הביצוע לתוכנית נבדקת לפני המשך.'},
  "בתהליך בקורת":{st:"partial",phase:"line",official:true,
    desc:'הפק"ע נמצאת בביקורת איכות.'},
  "ביקורת חלקית":{st:"partial",phase:"line",official:true,
    desc:'חלק מהיחידות בפק"ע עברו ביקורת, השאר עדיין ממתינות.'},
  "ביקורת סופית":{st:"partial",phase:"line",official:true,
    desc:'הפק"ע בביקורת הסופית שלפני השחרור והאריזה.'},
  "ממתין לאריזה":{st:"partial",phase:"line",official:true,
    desc:'הייצור הסתיים והפק"ע ממתינה בתור לאריזה — עדיין בתוך התהליך.'},
  // ── עצורה (בתהליך ייצור, אבל תקועה) ─────────────────────────────────────
  "חוסרים ביצור":{st:"blocked",phase:"stuck",official:true,
    desc:'חסרים רכיבים בקו הייצור עצמו — הפק"ע נעצרה באמצע המסלול.'},
  "בעיה הנדסית":{st:"blocked",phase:"stuck",official:true,
    desc:'הייצור נעצר בגלל בעיה הנדסית — שרטוט, תוכנית, הוראת עבודה או תקלה טכנית שדורשת החלטה של הנדסה.'},
  'בעית ח"ג חסר':{st:"blocked",phase:"stuck",official:true,
    desc:'חסר חומר גלם. הפק"ע לא יכולה להתקדם עד שהחומר יגיע.'},
  // ── הסתיימה ─────────────────────────────────────────────────────────────
  "דווח אחרון":{st:"complete",phase:"done",official:true,
    desc:'הפעולה האחרונה במסלול דווחה — הפק"ע עברה את כל התהליך.'},
  "נסגרה":{st:"complete",phase:"done",official:true,
    desc:'הפק"ע נסגרה ב-ERP. לא צפויה עליה עוד עבודה.'},
  // ── לא להציג ────────────────────────────────────────────────────────────
  "מבוטלת":{st:"complete",phase:"cancelled",official:true,
    desc:'הפק"ע בוטלה ולא תיוצר. לפי הגדרת התהליך היא לא מוצגת — מדולגת בייבוא, ומוסתרת מהרשימות ומהדשבורד אם היא כבר במערכת.'},

  // ── ערכים שאינם ברשימה הרשמית, נשמרים כרשת ביטחון ──────────────────────
  "פקע COC":{st:"complete",phase:"done",
    desc:'הפק"ע קיבלה COC (תעודת התאמה) — סופקה ואושרה. פק"ע גמורה.'},
  "בוטלה":{st:"complete",phase:"cancelled",
    desc:'ניסוח אחר של ״מבוטלת״ — הפק"ע בוטלה ולא תיוצר, ואינה מוצגת.'},
  "דווח ראשון":{st:"partial",phase:"line",
    desc:'הדיווח הראשון על הפק"ע נקלט — הפעולה הראשונה במסלול בוצעה.'},
  "חיווט":{st:"partial",phase:"line",desc:'הפק"ע נמצאת בשלב החיווט.'},
  "ביצור קבמ":{st:"partial",phase:"line",desc:'הפק"ע בייצור בקו הקב"מ (קבלן משנה / קו ייעודי).'},
  'מוכן לקב"מ':{st:"partial",phase:"line",desc:'החלק הפנימי הסתיים והפק"ע ממתינה להעברה לקב"מ.'},
  "סיום יצור":{st:"partial",phase:"line",desc:'פעולות הייצור הסתיימו. הפק"ע ממתינה לביקורת, לאריזה או לסגירה.'},
  "ביקורת ראשונ":{st:"partial",phase:"line",desc:'ביקורת ראשונה (ביקורת פתיחה / First Article) מתבצעת על הפק"ע.'},
  "תהליך מבקר":{st:"partial",phase:"line",desc:'הפק"ע נמצאת אצל המבקר.'},
  "ממתין למבקר":{st:"partial",phase:"line",desc:'הפק"ע ממתינה בתור למבקר — זמן המתנה, לא זמן עבודה.'},
  "ממתין א.FAI":{st:"partial",phase:"line",desc:'הפק"ע ממתינה לאישור FAI (בדיקת פריט ראשון) לפני שאפשר להמשיך.'},
  "אריזה":{st:"partial",phase:"line",desc:'הפק"ע נארזת למשלוח.'},
  "בתהליך סגירה":{st:"partial",phase:"line",desc:'הפק"ע בתהליך סגירה ב-ERP — הדיווחים נסגרים והעלויות נאספות.'},
  "בעית כלי חסר":{st:"blocked",phase:"stuck",desc:'חסר כלי או ציוד ייעודי (Tooling, ג\'יג, מכשור) שנדרש לפעולה.'},
  "חוסר נגדי":{st:"blocked",phase:"stuck",desc:'רכיב של הפק"ע נלקח לטובת פק"ע אחרת (חוסר נגדי), והיא ממתינה להשלמה.'},
  "הוקפאה":{st:"blocked",phase:"stuck",desc:'הפק"ע הוקפאה בהחלטת ניהול — שינוי עדיפויות, המתנה ללקוח או לתקציב.'},
  "הוחזר לתיקון":{st:"blocked",phase:"stuck",desc:'הפק"ע חזרה לתיקון אחרי שנפסלה בביקורת או בבדיקה.'},
  "בטיפול לקוח":{st:"blocked",phase:"stuck",desc:'הפק"ע ממתינה להחלטה, לאישור או לחומר מהלקוח.'}
};
// Priority statuses get renamed and added to over time, so an unfamiliar one is
// still placed sensibly instead of silently landing on "open" — and the guess
// says which phase it belongs to as well, because that is what the filters read.
function priStatus(raw){
  const s=String(raw==null?"":raw).trim();
  const out=(st,phase,guessed,desc,official)=>({st,phase,guessed,official:!!official,desc:desc||"",raw:s});
  if(!s)return out("open","pre",false,'הקובץ לא נשא סטטוס פק"ע לשורה הזו — היא נכנסת כפתוחה שתהליך הייצור שלה לא התחיל.');
  const hit=PRI_STATUS_INFO[s];
  if(hit)return out(hit.st,hit.phase,false,hit.desc,hit.official);
  const g='הסטטוס הזה אינו ברשימת הסטטוסים המוכרים של Priority — הוא שויך לפי הניסוח שלו. אפשר לעדכן את הפק"ע ידנית אם השיוך שגוי.';
  if(/בוטל|מבוטל/.test(s))return out("complete","cancelled",true,g);
  if(/בעי|חוסר|חסר|הוקפא|מוקפא|תקוע|עיכוב/.test(s))return out("blocked","stuck",true,g);
  if(/coc|נסגר|הושלמ|דווח אחרון/i.test(s))return out("complete","done",true,g);
  // Only פתוחה and שוחררה are before the process starts — everything else that
  // sounds early (הודפסה, ממתין ליצור, קדם יצור) is already inside it.
  if(/שוחרר|פתוח|טרם/.test(s))return out("open","pre",true,g);
  return out("partial","line",true,g);
}
// A פק"ע the ERP calls מבוטלת is not history to browse — the process says do not
// show it. It is skipped on import, and one already in the app is kept (so the
// hours somebody reported against it are not silently erased) but held out of
// every list and every figure unless it is asked for by name.
const isCancelled=o=>orderPhase(o)==="cancelled";
// פקע COC never enters the app — see priBuild and the Excel importer.
const isCocStatus=raw=>/^פקע\s*coc$/i.test(String(raw==null?"":raw).trim());
// "נתונים בלבד": a פק"ע that is either not yet on the line (פתוחה) or already
// past it (דווח ראשון / דווח אחרון / נסגרה). Nobody schedules or reports work on
// it, but it is real production, so the dashboard and the reports still count it.
// It is kept out of the פק"ע list (except under its own chip), out of the work
// queue and out of the פק"ע picker a manager schedules from.
const DATA_ONLY_STATUSES=new Set(["פתוחה","דווח ראשון","דווח אחרון","נסגרה"]);
const isDataOnly=o=>DATA_ONLY_STATUSES.has(String(o?.erpStatus||"").trim());
// The phase a פק"ע is in, from whatever the ERP said about it. Orders imported
// before the raw status was kept have nothing to read, so the app status stands
// in: "פתוחה" there means nothing was reported, which is the pre-line case.
function orderPhase(order){
  const raw=String(order?.erpStatus||"").trim();
  if(raw)return priStatus(raw).phase;
  const st=order?.status||"open";
  return st==="blocked"?"stuck":st==="complete"?"done":st==="partial"?"line":"pre";
}
// What the ERP said, spelled out — the label, its explanation, and the free-text
// note the file carried beside it (when it did). This is what the פק"ע card shows
// under "סיבת התקיעה" for a blocked order.
function orderErpInfo(order){
  const raw=String(order?.erpStatus||"").trim();
  const note=String(order?.erpNote||"").trim();
  if(!raw)return note?{raw:"",desc:"",note,guessed:false}:null;
  const i=priStatus(raw);
  return{raw,desc:i.desc,note,guessed:i.guessed};
}
// The Priority sheet is read by exactly the same rules as every other workbook —
// see xlNum. It used to have its own digit-scraping copy, which is how a
// date-formatted מחיר column became a fifteen-digit price.
const priNum=xlNum;
// Priority writes a literal 0 into its code columns (סניף / פרויקט) for "none".
const priTxt=v=>{const s=String(v==null?"":v).trim();return(s==="0"||s==="-")?"":s};
// The second sheet of the export: the serial numbers Priority already issued,
// one row per unit. Its headers use a geresh where the route sheet uses a
// gershayim, which xlNorm strips either way.
const PRI_S={wo:"פק'ע",pn:"מק'ט",sn:"SN",qty:"כ. הפק'ע",status:"סטטוס פק'ע"};
const PRI_SKIP="__skip",PRI_NEW="__new",PRI_MAP_LS="priorityStageMap";
// Progress imported from the ERP is booked against a stand-in "worker" so it never
// lands in anybody's performance report — no person did this work in the app.
const PRI_LOG_USER="priority_import",PRI_LOG_NAME="ייבוא Priority",XL_LOG_NAME="ייבוא Excel";
// Imported history is dated by the פק"ע's release date, so it falls in the right
// year in the dashboards instead of all landing on the day of the import.
const priStamp=iso=>{
  const d=String(iso||"").slice(0,10);
  return /^\d{4}-\d{2}-\d{2}$/.test(d)&&d<=todays()?`${d}T08:00:00.000Z`:nowISO();
};

// Is this a Priority export? Judged on the header rows alone, so a renamed sheet
// or an extra column at the end still matches. Returns the route sheet and, when
// the export carries one, the serials sheet beside it.
function priDetect(wb){
  const headOf=n=>(XLSX.utils.sheet_to_json(wb.Sheets[n],{header:1,defval:""})[0]||[]).map(xlNorm);
  let routes=null,serials=null;
  for(const n of wb.SheetNames){
    const head=headOf(n),has=k=>head.includes(xlNorm(k));
    const wo=has(PRI_H.wo)||has(PRI_S.wo);
    if(!wo)continue;
    if(!routes&&has(PRI_H.opDesc)&&(has(PRI_H.wc)||has(PRI_H.op)))routes=wb.Sheets[n];
    else if(!serials&&(has(PRI_S.sn)||has("S/N")))serials=wb.Sheets[n];
  }
  return routes?{routes,serials}:null;
}

// Pass 1 — fold the operation rows into orders and collect the distinct
// operations, without yet deciding which app stage each one becomes. That
// decision belongs to the user, and changing it must not re-read the file.
function priScan(rows,serialRows){
  const wos=new Map(),ops=new Map();
  let skipped=0;
  rows.forEach((r,i)=>{
    const wo=String(xlGet(r,PRI_H.wo)||"").trim();
    if(!wo){skipped++;return}
    let o=wos.get(wo);
    if(!o){
      o={wo,pn:String(xlGet(r,PRI_H.pn)||"").trim(),desc:String(xlGet(r,PRI_H.desc)||"").trim(),
        project:priTxt(xlGet(r,PRI_H.project)),branch:branchCode(xlGet(r,PRI_H.branch)),
        qty:priNum(xlGet(r,PRI_H.qty)),price:priNum(xlGet(r,PRI_H.price)),
        release:xlDate(xlGet(r,PRI_H.release)),endDate:xlDate(xlGet(r,PRI_H.endDate)),
        statusRaw:String(xlGet(r,PRI_H.status)||"").trim(),
        note:String(xlGet(r,...PRI_NOTE_H)||"").trim(),row:i+2,ops:[],sns:[]};
      wos.set(wo,o);
    }
    // The note lives on the פק"ע, but the export repeats the header fields on
    // every operation row and only some of them carry it — so the first row that
    // has one wins rather than only the first row of the group.
    if(!o.note){const n=String(xlGet(r,...PRI_NOTE_H)||"").trim();if(n)o.note=n}
    const name=String(xlGet(r,PRI_H.opDesc)||"").trim();
    const code=String(xlGet(r,PRI_H.op)||"").trim();
    const wc=String(xlGet(r,PRI_H.wc)||"").trim();
    const seq=priNum(xlGet(r,PRI_H.seq,PRI_H.seqAlt));
    // The מק"ט-level standard is the one the app stores; the פק"ע-level column
    // only fills in where Priority has no standard for the part itself.
    const std=priNum(xlGet(r,PRI_H.stdPn))||priNum(xlGet(r,PRI_H.stdWo));
    o.ops.push({key:xlNorm(name),name,seq,std,code,wc,
      reported:priNum(xlGet(r,PRI_H.reported)),remain:priNum(xlGet(r,PRI_H.remain))});
    if(!name)return;
    let op=ops.get(xlNorm(name));
    if(!op){op={key:xlNorm(name),name,count:0,seqs:[],codes:new Set(),centers:new Set()};ops.set(op.key,op)}
    op.count++;
    if(seq)op.seqs.push(seq);
    if(code)op.codes.add(code);
    if(wc)op.centers.add(wc);
  });
  // Serial numbers come from the export's second sheet, matched to their פק"ע.
  // Priority only reuses a serial across different פק"ע, never inside one, so the
  // duplicate check is per order.
  let snOrphan=0,snDup=0,snPn=0,snRows=0;
  (serialRows||[]).forEach(r=>{
    const wo=String(xlGet(r,PRI_S.wo,PRI_H.wo,"WO")||"").trim();
    const sn=String(xlGet(r,PRI_S.sn,"S/N",'מס"ד',"סידורי")||"").trim();
    if(!wo&&!sn)return;
    snRows++;
    const o=wos.get(wo);
    if(!o||!sn){snOrphan++;return}
    if(o.sns.some(x=>x.sn===sn)){snDup++;return}
    const pn=String(xlGet(r,PRI_S.pn,PRI_H.pn)||"").trim();
    if(pn&&o.pn&&pn!==o.pn)snPn++;
    o.sns.push({sn});
  });

  // A new stage's place in the route is the sequence number Priority gives that
  // operation most often — the median, so one odd route can't drag it out of line.
  const list=[...ops.values()].map(o=>{
    const s=o.seqs.slice().sort((a,b)=>a-b);
    return{key:o.key,name:o.name,count:o.count,codes:[...o.codes],centers:[...o.centers],
      seq:s.length?s[Math.floor(s.length/2)]:0};
  }).sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name));
  return{wos:[...wos.values()],ops:list,skipped,rows:rows.length,
    serials:{rows:snRows,orphan:snOrphan,dup:snDup,pnMismatch:snPn,
      wos:[...wos.values()].filter(w=>w.sns.length).length}};
}

// The global running order for the operations in the file.
//
// Priority numbers the steps *within* each route (שלה בפק"ע), and those numbers
// don't line up between routes — the military route counts 20,30,40 over the same
// ground the civil one calls 10..220. Ordering the new stages by their own numbers
// would therefore shuffle the families into each other. What every route does
// agree on is which operation comes *before* which, so the order is read off that:
// a topological sort of "A precedes B", with the typical step number breaking ties
// (and freeing the earliest operation whenever routes genuinely contradict).
function priOpOrder(scan){
  const keys=scan.ops.map(o=>o.key);
  const pos=new Map(keys.map((k,i)=>[k,i]));
  const seqOf=new Map(scan.ops.map(o=>[o.key,o.seq||9999]));
  const next=new Map();
  scan.wos.forEach(w=>{
    const route=[];
    w.ops.slice().sort((a,b)=>(a.seq||0)-(b.seq||0)).forEach(op=>{if(op.key&&!route.includes(op.key))route.push(op.key)});
    for(let i=0;i+1<route.length;i++){
      let set=next.get(route[i]);if(!set){set=new Set();next.set(route[i],set)}
      set.add(route[i+1]);
    }
  });
  const left=new Set(keys),out=[];
  while(left.size){
    const deg=new Map([...left].map(k=>[k,0]));
    left.forEach(a=>(next.get(a)||[]).forEach(b=>{if(deg.has(b))deg.set(b,deg.get(b)+1)}));
    let pool=[...left].filter(k=>!deg.get(k));
    if(!pool.length)pool=[...left];                     // routes disagree — take the earliest step
    pool.sort((a,b)=>(seqOf.get(a)-seqOf.get(b))||(pos.get(a)-pos.get(b)));
    left.delete(pool[0]);out.push(pool[0]);
  }
  return out;
}

// Suggested operation → stage mapping: an existing stage of the same name wins,
// otherwise the operation becomes a new stage. Whatever the user chose on an
// earlier import beats both — that is the point of saving it.
function priAutoMap(ops,stages,saved){
  const byName=new Map((stages||[]).map(s=>[xlNorm(s.name),s.id]));
  const live=new Set((stages||[]).map(s=>s.id));
  const m={};
  (ops||[]).forEach(o=>{
    const prev=saved&&saved[o.key];
    if(prev===PRI_SKIP||prev===PRI_NEW||(prev&&live.has(prev))){m[o.key]=prev;return}
    m[o.key]=byName.get(o.key)||PRI_NEW;
  });
  return m;
}

// Pass 2 — turn the scan plus the user's choices into everything that has to be
// created: the orders, the stages and projects that don't exist yet, and one
// זמן תקן record per מק"ט built from the ז.תקן column.
function priBuild(scan,ctx,map,opts){
  const {projects=[],stages=[],pnStandards=[]}=ctx||{};
  const {onlyOpen=false,skipCancelled=true,makeStages=true,makeProjects=true,importStd=true,fillSerials=false,serialMax=100,importProgress=true}=opts||{};
  const issues=[],addIssue=(level,msg)=>{if(issues.length<300)issues.push({level,msg})};

  // ── stages ────────────────────────────────────────────────────────────
  // Existing stages keep their configured order untouched; new ones are appended
  // after them, among themselves in Priority's own sequence.
  const newStages=[];
  const stageOf=new Map();                                  // op key → stage id
  const maxOrder=stages.reduce((m,s)=>Math.max(m,Number(s.order)||0),0);
  const byKey=new Map(scan.ops.map(o=>[o.key,o]));
  if(makeStages)priOpOrder(scan).filter(k=>map[k]===PRI_NEW).forEach((k,i)=>{
    const st={id:uid(),name:byKey.get(k).name,order:maxOrder+i+1,
      color:COLORS[(stages.length+i)%COLORS.length],price:0,hourlyRate:0,roleId:"",minutes:0};
    newStages.push(st);stageOf.set(k,st.id);
  });
  scan.ops.forEach(o=>{const c=map[o.key];if(c&&c!==PRI_NEW&&c!==PRI_SKIP)stageOf.set(o.key,c)});

  // ── projects ──────────────────────────────────────────────────────────
  const projByName=new Map(projects.map(p=>[xlNorm(p.name),p.id]));
  const newProjects=[];
  const projectOf=code=>{
    if(!code)return"";
    const hit=projByName.get(xlNorm(code));
    if(hit)return hit;
    if(!makeProjects)return"";
    const p={id:uid(),name:code};
    newProjects.push(p);projByName.set(xlNorm(code),p.id);
    return p.id;
  };

  // ── orders ────────────────────────────────────────────────────────────
  const orders=[];let closedSkipped=0,cancelledSkipped=0,cocSkipped=0,noBranchSkipped=0,noStage=0,guessed=0,serialTotal=0,serialCapped=0,noQty=0,serialFilled=0,fromSheet=0;
  // Skipped מבוטלת are still reported by number: a פק"ע that is already in the
  // app and has since been cancelled has to be marked, or it lingers in the list
  // looking live because the file that cancelled it left it out.
  const cancelledWos=[];
  // Progress carried over from the ERP — see the block inside the loop.
  const logs=[];let progWos=0,progQtyWos=0,progNoSerials=0,progClamped=0;
  scan.wos.forEach(w=>{
    const s=priStatus(w.statusRaw);
    if(s.guessed)guessed++;
    // מבוטלת means "do not show" — so by default it does not come in at all.
    if(s.phase==="cancelled"){if(skipCancelled){cancelledSkipped++;cancelledWos.push({wo:w.wo,statusRaw:w.statusRaw});return}}
    else if(onlyOpen&&s.st==="complete"){closedSkipped++;return}
    // פקע COC was delivered and signed for — nothing is left to do on it and
    // nothing to measure, so it does not come in at all.
    if(isCocStatus(w.statusRaw)){cocSkipped++;return}
    // A פק"ע without a סניף belongs to no division and no manager can see it.
    if(!branchCode(w.branch)){noBranchSkipped++;return}
    // The route is this פק"ע's own, in its own order: the stages it actually has,
    // sequenced by שלב בפק"ע. Not a subset of one company-wide route — two פק"ע
    // can run the same two operations in opposite order, and both are right.
    const ids=[];
    w.ops.slice().sort((a,b)=>(a.seq||0)-(b.seq||0))
      .forEach(op=>{const sid=stageOf.get(op.key);if(sid&&!ids.includes(sid))ids.push(sid)});
    if(!ids.length)noStage++;
    if(!w.qty)noQty++;
    // Ids are derived from the order's own id, so a bulk run can't collide.
    const oid=uid(),serials=[];
    if(w.sns.length){
      // The real serial numbers Priority issued — used as they are.
      w.sns.forEach((x,k)=>serials.push({id:`${oid}s${k+1}`,sn:x.sn,createdAt:nowISO()}));
      fromSheet++;
    }else if(fillSerials&&w.qty>0){
      // Nothing issued for this פק"ע yet: stand-in serials so work can be logged.
      const cap=Number(serialMax)||0,n=cap>0?Math.min(w.qty,cap):w.qty;
      if(n<w.qty)serialCapped++;
      const prefix=w.pn||w.wo;
      for(let k=1;k<=n;k++)serials.push({id:`${oid}s${k}`,sn:`${prefix}-${String(k).padStart(4,"0")}`,createdAt:nowISO()});
      serialFilled++;
    }
    serialTotal+=serials.length;

    // ── progress ────────────────────────────────────────────────────────
    // Priority already knows how far each operation got: כמות מדווחת is how many
    // units were reported through it, יתרה לבצוע how many are still owed. The app
    // holds the same fact in a different shape — one completed work log per unit
    // per stage — and *that* is what every progress bar, unit count, WIP figure
    // and remaining-work estimate reads. Without this translation a פק"ע that is
    // three quarters built arrives looking untouched, and a whole ERP's worth of
    // history reads as "everything is open".
    //
    // Which physical unit did what is not in the file; how many did, is. So the
    // units are taken from the front of the list — operations report
    // non-increasing counts down the route, which makes unit #1 the furthest
    // along and keeps the picture consistent from stage to stage.
    if(importProgress&&(s.st==="complete"||w.ops.some(op=>op.reported>0||op.remain>0))){
      // What the progress can be spread over: the serials the פק"ע has, or — when
      // it has none — the quantity it was opened for, recorded as a quantity
      // signature instead. A פק"ע that is not managed serially used to lose its
      // ERP progress entirely here and arrive looking untouched.
      const cap=serials.length||(Number(w.qty)||0);
      if(!cap)progNoSerials++;
      else{
        const perStage=new Map();
        w.ops.forEach(op=>{
          const sid=stageOf.get(op.key);if(!sid)return;
          // The reported count is the direct answer. Where Priority left it blank
          // but did fill in a remainder, "ordered minus what is left" says the
          // same thing; a remainder of zero is too often an empty cell to trust.
          let n=op.reported>0?op.reported:((w.qty>0&&op.remain>0&&op.remain<w.qty)?w.qty-op.remain:0);
          n=Math.floor(n);
          if(!(n>0))return;
          if(n>cap)progClamped++;
          perStage.set(sid,Math.max(perStage.get(sid)||0,Math.min(n,cap)));
        });
        // A פק"ע Priority calls closed has, by definition, been through its whole
        // route — even when the operation counters in the export are blank.
        if(s.st==="complete")ids.forEach(sid=>perStage.set(sid,cap));
        let k=0;
        perStage.forEach((n,sid)=>{
          // No serials — one signature for the stage, carrying the count. Which
          // physical unit did what is not invented, because the file never said.
          if(!serials.length){
            logs.push({id:`${oid}q${k++}`,userId:PRI_LOG_USER,userName:PRI_LOG_NAME,
              serialId:null,serialSn:null,stageId:sid,orderId:oid,
              startTime:priStamp(w.release),endTime:priStamp(w.release),completed:true,
              durationMin:0,paused:false,pauseStart:null,totalPauseMin:0,pauseLog:[],
              bulk:true,bulkGroupId:null,bulkCount:n});
            return;
          }
          for(let u=0;u<n;u++){
            const sr=serials[u];
            logs.push({id:`${oid}p${k++}`,userId:PRI_LOG_USER,userName:PRI_LOG_NAME,
              serialId:sr.id,serialSn:sr.sn,stageId:sid,orderId:oid,
              startTime:priStamp(w.release),endTime:priStamp(w.release),completed:true,
              // Deliberately zero: the file says a unit passed the stage, never how
              // long it took, and a made-up duration would poison זמן בפועל.
              durationMin:0,paused:false,pauseStart:null,totalPauseMin:0,pauseLog:[],
              bulk:false,bulkGroupId:null,bulkCount:null});
          }
        });
        if(k){progWos++;if(!serials.length)progQtyWos++}
      }
    }

    orders.push({id:oid,woNumber:w.wo,pn:w.pn,description:w.desc,qty:w.qty,unitPrice:w.price,
      projectId:projectOf(w.project),branch:branchCode(w.branch),receivedDate:w.release,targetDate:w.endDate,status:s.st,
      // The ERP's own wording, kept. The four app statuses cannot tell "שוחררה"
      // from "הועבר לייצור", nor say *why* a פק"ע is stuck — this can.
      erpStatus:w.statusRaw||"",erpNote:w.note||"",
      stageIds:ids,serials,shortages:[],defects:[],deliveredSerials:[],
      // Preview only — stripped before the order reaches the app's state.
      _pri:{statusRaw:w.statusRaw,project:w.project,ops:w.ops.length,
        reported:w.ops.length?Math.min(...w.ops.map(o=>o.reported)):0,
        remain:w.ops.length?Math.max(...w.ops.map(o=>o.remain)):0}});
  });

  // ── זמן תקן per מק"ט ──────────────────────────────────────────────────
  // Priority's ז.תקן ליח' is standard minutes per unit per operation, which is
  // exactly the shape of a pn_standards record. Stages the file says nothing
  // about keep whatever the app already had.
  const stds=[];let stdConflicts=0;
  if(importStd){
    const perPn=new Map();
    scan.wos.forEach(w=>{
      if(!w.pn)return;
      let m=perPn.get(w.pn);if(!m){m=new Map();perPn.set(w.pn,m)}
      w.ops.forEach(op=>{
        const sid=stageOf.get(op.key);
        if(!sid||!(op.std>0))return;
        const cur=m.get(sid);
        if(cur===undefined){m.set(sid,op.std);return}
        if(Math.abs(cur-op.std)>0.001){stdConflicts++;m.set(sid,Math.max(cur,op.std))}
      });
    });
    const existing=pnStdIndex(pnStandards);
    perPn.forEach((m,pn)=>{
      if(!m.size)return;
      const prev=existing.get(pnKey(pn));
      const stageMin={...(prev?.stageMin||{})};
      m.forEach((v,sid)=>{stageMin[sid]=Math.round(v*10)/10});
      stds.push({id:prev?.id||uid(),pn:pnKey(pn),stageMin,total:Number(prev?.total||0),
        note:prev?.note||"",updatedBy:"Priority",updatedAt:nowISO()});
    });
    if(stdConflicts)addIssue("info",`${stdConflicts} זמני תקן נתנו ערך שונה לאותו מק"ט ושלב בפק"ע שונות — נלקח הגבוה`);
  }

  const unmapped=scan.ops.filter(o=>!stageOf.has(o.key));
  if(unmapped.length)addIssue("info",`${unmapped.length} פעולות אינן משויכות לשלב — ${unmapped.slice(0,4).map(o=>o.name).join(" · ")}${unmapped.length>4?" ...":""}`);
  if(noStage)addIssue("warn",`${noStage} פק"ע ללא שלבים — כל הפעולות שלהן לא שויכו`);
  if(noQty)addIssue("warn",`${noQty} פק"ע ללא כמות`);
  if(guessed)addIssue("info",`${guessed} פק"ע עם סטטוס Priority שאינו ברשימה — שויך לפי הדמיון`);
  if(closedSkipped)addIssue("info",`${closedSkipped} פק"ע סגורות (COC / נסגרה / דווח אחרון) לא יובאו`);
  if(cancelledSkipped)addIssue("info",`${cancelledSkipped} פק"ע מבוטלות לא יובאו — לפי הגדרת התהליך הן לא מוצגות`);
  if(cocSkipped)addIssue("info",`${cocSkipped} פק"ע בסטטוס פקע COC לא יובאו`);
  if(noBranchSkipped)addIssue("info",`${noBranchSkipped} פק"ע ללא סניף לא יובאו`);
  if(scan.skipped)addIssue("info",`${scan.skipped} שורות ללא מספר פק"ע — דולגו`);
  if(serialCapped)addIssue("warn",`${serialCapped} פק"ע קיבלו פחות סידוריים מהכמות בגלל התקרה`);
  if(progQtyWos)addIssue("info",`${progQtyWos} פק"ע ללא סידוריים קיבלו את ההתקדמות שלהן כחתימה לפי כמות — אפשר להמשיך לחתום עליהן בכרטיס הפק"ע`);
  if(progNoSerials)addIssue("warn",`${progNoSerials} פק"ע עם התקדמות בקובץ אך ללא סידוריים וללא כמות — ההתקדמות לא נרשמה`);
  if(progClamped)addIssue("info",`${progClamped} פעולות דיווחו יותר יחידות ממספר הסידוריים בפק"ע — נרשמו עד מספר הסידוריים`);
  const sn=scan.serials||{};
  if(sn.orphan)addIssue("warn",`${sn.orphan} שורות בגיליון הסידוריים ללא פק"ע מתאימה — דולגו`);
  if(sn.dup)addIssue("warn",`${sn.dup} סידוריים כפולים באותה פק"ע — דולגו`);
  if(sn.pnMismatch)addIssue("info",`${sn.pnMismatch} סידוריים עם מק"ט שונה מזה שבגיליון הפעולות — נלקח המק"ט של הפק"ע`);

  return{mode:"priority",orders,newStages,newProjects,stds,logs,issues,cancelledWos,opStage:Object.fromEntries(stageOf),
    stats:{orders:orders.length,rows:scan.rows,ops:scan.ops.length,mapped:stageOf.size,
      byBranch:orders.reduce((m,o)=>{const c=branchCode(o.branch)||"—";m[c]=(m[c]||0)+1;return m},{}),
      serials:serialTotal,serialWos:fromSheet,serialFilled,sheetSerials:(scan.serials||{}).rows||0,
      defects:0,shortages:0,logs:logs.length,progWos,progQtyWos,progNoSerials,
      byStatus:orders.reduce((m,o)=>{m[o.status]=(m[o.status]||0)+1;return m},{}),
      byPhase:orders.reduce((m,o)=>{const p=orderPhase(o);m[p]=(m[p]||0)+1;return m},{}),
      // Every distinct סטטוס פק"ע the file actually carried, with its count — the
      // legend the import screen prints so nobody has to guess what a status meant.
      byRaw:(()=>{const m=new Map();orders.forEach(o=>{const k=String(o.erpStatus||"").trim()||"(ריק)";
        const e=m.get(k)||{raw:k,n:0,st:o.status,phase:orderPhase(o)};e.n++;m.set(k,e)});
        return[...m.values()].sort((a,b)=>PHASE_ORDER.indexOf(a.phase)-PHASE_ORDER.indexOf(b.phase)||b.n-a.n)})(),
      newStages:newStages.length,newProjects:newProjects.length,stds:stds.length,closedSkipped,cancelledSkipped,cocSkipped,noBranchSkipped,
      // How many מבוטלת the file carries at all, whether or not they are skipped.
      cancelledInFile:scan.wos.filter(w=>priStatus(w.statusRaw).phase==="cancelled").length}};
}
// ── ייבוא חוזר: עדכון במקום כפילות ────────────────────────────────────────
// The Priority report is a snapshot of everything currently open, so the same
// פק"ע comes back in every file that is pulled. "הוסף לקיימים" used to append it
// a second time, and the list filled with pairs of the same order whose route,
// serial numbers and progress were split between two rows.
//
// It now matches on מספר פק"ע and updates the row that is already there. Who owns
// what is the whole of the rule:
//
//   the ERP owns   סטטוס · כמות · מחיר · פרויקט · סניף · תאריכים · מסלול הפעולות
//   the app owns   הסידוריים שעבדו עליהם · תקלות · חוסרים · אספקות · דיווחי העובדים
//
// A פק"ע whose ERP fields and reported progress are identical to what is already
// stored is left alone entirely — not rewritten, not re-synced — which is what
// makes a monthly file of thousands of orders land as the handful that moved.
const MERGE_FIELDS=[
  ["status","סטטוס"],["erpStatus",'סטטוס פק"ע'],["erpNote","הערת סטטוס"],
  ["qty","כמות"],["unitPrice","מחיר ליחידה"],["projectId","פרויקט"],["branch","סניף"],
  ["receivedDate","תאריך שחרור"],["targetDate","תאריך סיום ייצור"],
  ["description","תיאור"],["pn",'מק"ט']
];
const woKey=w=>String(w==null?"":w).trim().toLowerCase();
const snKey=s=>String(s==null?"":s).trim().toLowerCase();
// stageId → units, from a set of import logs. Per-unit records count one each,
// a quantity signature carries its count.
function progPerStage(logs){
  const m=new Map();
  (logs||[]).forEach(w=>{if(!w.stageId)return;m.set(w.stageId,(m.get(w.stageId)||0)+(isQtyLog(w)?(Number(w.bulkCount)||0):1))});
  return m;
}
const progSig=m=>[...m.entries()].filter(([,n])=>n>0).sort((a,b)=>a[0]<b[0]?-1:1).map(([k,n])=>k+":"+n).join("|");
// The import's progress records for one order, drawn against the serials that
// order actually ends up with. Regenerated rather than re-pointed, because the
// order the file describes and the order already stored can differ in whether
// they are managed serially at all.
function priRelog(order,perStage,stamp){
  const out=[],serials=order.serials||[],cap=serials.length||(Number(order.qty)||0);
  if(!cap)return out;
  let k=0;
  perStage.forEach((n0,sid)=>{
    const n=Math.min(Math.floor(n0)||0,cap);
    if(!(n>0))return;
    if(!serials.length){
      out.push({id:`${order.id}q${k++}`,userId:PRI_LOG_USER,userName:PRI_LOG_NAME,
        serialId:null,serialSn:null,stageId:sid,orderId:order.id,
        startTime:stamp,endTime:stamp,completed:true,
        durationMin:0,paused:false,pauseStart:null,totalPauseMin:0,pauseLog:[],
        bulk:true,bulkGroupId:null,bulkCount:n});
      return;
    }
    for(let u=0;u<n;u++){
      const sr=serials[u];
      out.push({id:`${order.id}p${k++}`,userId:PRI_LOG_USER,userName:PRI_LOG_NAME,
        serialId:sr.id,serialSn:sr.sn,stageId:sid,orderId:order.id,
        startTime:stamp,endTime:stamp,completed:true,
        durationMin:0,paused:false,pauseStart:null,totalPauseMin:0,pauseLog:[],
        bulk:false,bulkGroupId:null,bulkCount:null});
    }
  });
  return out;
}
// Plans a "הוסף לקיימים" run without applying it: which orders are new, which
// change and in what, which are already up to date, and the exact logs to write
// and to drop. `built` is what priBuild produced; `existing` the app's orders;
// `workLogs` everything reported so far, app and ERP alike.
function priMergePlan(built,existing,workLogs){
  const byWo=new Map();
  (existing||[]).forEach(o=>{const k=woKey(o.woNumber);if(k&&!byWo.has(k))byWo.set(k,o)});
  const logsByOrder=new Map();
  (built.logs||[]).forEach(w=>{const a=logsByOrder.get(w.orderId);a?a.push(w):logsByOrder.set(w.orderId,[w])});
  // Only the ERP's own records are replaced on a re-import — a person's reported
  // work is never touched by a file.
  const erpByOrder=new Map();
  (workLogs||[]).forEach(w=>{if(w.userId!==PRI_LOG_USER)return;const a=erpByOrder.get(w.orderId);a?a.push(w):erpByOrder.set(w.orderId,[w])});

  const added=[],updated=[],changes=[],logs=[],dropLogIds=[];
  let unchanged=0,newSerials=0,progressChanged=0;

  (built.orders||[]).forEach(b=>{
    const {_pri,...bo}=b;
    const prev=byWo.get(woKey(bo.woNumber));
    const bLogs=logsByOrder.get(b.id)||[];
    const stamp=(bLogs[0]&&bLogs[0].startTime)||nowISO();
    const perStage=progPerStage(bLogs);
    if(!prev){
      added.push(bo);
      logs.push(...bLogs);
      return;
    }
    // ── the row already exists: update it in place ────────────────────────
    const fields=[];
    const next={...prev};
    MERGE_FIELDS.forEach(([k,label])=>{
      const v=bo[k];
      // A field the file left empty is not an instruction to erase what is stored.
      if(v===""||v===null||v===undefined)return;
      const a=k==="qty"||k==="unitPrice"?Number(prev[k]||0):String(prev[k]||"");
      const c=k==="qty"||k==="unitPrice"?Number(v||0):String(v||"");
      if(a===c)return;
      next[k]=v;fields.push(label);
    });
    // A reason belongs to the stoppage that caused it. Once the ERP says the פק"ע
    // is moving again, last month's "ממתין לנגדים מהספק" is not a fact any more —
    // it is a stale line on the card that reads as current. It goes with the
    // stoppage, unless the file supplied a new one.
    if(prev.erpNote&&!bo.erpNote&&orderPhase(prev)==="stuck"&&orderPhase(next)!=="stuck"){
      next.erpNote="";fields.push("סיבת התקיעה נוקתה");
    }
    // The route belongs to the ERP, but an empty one in the file means "no
    // operation was mapped to a stage", not "this פק"ע has no route".
    if((bo.stageIds||[]).length&&String((prev.stageIds||[]).join(","))!==String(bo.stageIds.join(","))){
      next.stageIds=bo.stageIds;fields.push("מסלול");
    }
    // Serial numbers are added, never removed — a unit somebody already reported
    // work on does not disappear because this month's report stopped listing it.
    const have=new Map((prev.serials||[]).map(sr=>[snKey(sr.sn),sr]));
    const addSn=(bo.serials||[]).filter(sr=>sr.sn&&!have.has(snKey(sr.sn)));
    if(addSn.length){
      next.serials=[...(prev.serials||[]),...addSn.map((sr,i)=>({id:`${prev.id}n${Date.now().toString(36)}${i}`,sn:sr.sn,createdAt:nowISO()}))];
      fields.push(`${addSn.length} סידוריים חדשים`);
      newSerials+=addSn.length;
    }
    // Defects and shortages a filled-in template carries are added, never used to
    // wipe what the floor already recorded — matched on their own wording so the
    // same row in next month's file does not become a second open תקלה.
    const dKey=d=>[String(d.title||"").trim(),String(d.discoveredDate||"").slice(0,10)].join("|");
    const shKey=x=>[String(x.item||"").trim(),String(x.sku||"").trim()].join("|");
    const addDef=(bo.defects||[]).filter(d=>!(prev.defects||[]).some(p2=>dKey(p2)===dKey(d)));
    if(addDef.length){next.defects=[...(prev.defects||[]),...addDef];fields.push(`${addDef.length} תקלות`)}
    const addSh=(bo.shortages||[]).filter(x=>!(prev.shortages||[]).some(p2=>shKey(p2)===shKey(x)));
    if(addSh.length){next.shortages=[...(prev.shortages||[]),...addSh];fields.push(`${addSh.length} חוסרים`)}
    // Progress: compare what the file now says against what the last import left.
    const prevErp=erpByOrder.get(prev.id)||[];
    const sigNew=progSig(perStage),sigOld=progSig(progPerStage(prevErp));
    const progMoved=sigNew!==sigOld;
    if(!fields.length&&!progMoved){unchanged++;return}
    if(progMoved||next.serials!==prev.serials){
      // Redrawn against the serials this order ends up with, so a פק"ע that
      // gained serial numbers stops carrying its progress as a bare quantity.
      if(prevErp.length)dropLogIds.push(...prevErp.map(w=>w.id));
      logs.push(...priRelog(next,perStage,stamp));
      if(progMoved){progressChanged++;if(!fields.includes("התקדמות"))fields.push("התקדמות")}
    }
    updated.push(next);
    if(changes.length<400)changes.push({wo:next.woNumber,fields,
      from:String(prev.erpStatus||SL[prev.status||"open"]||""),to:String(next.erpStatus||SL[next.status||"open"]||"")});
  });
  // A פק"ע the file cancelled was skipped rather than built, so it never reached
  // the loop above. It is still a change to the row that is already here.
  let cancelled=0;
  (built.cancelledWos||[]).forEach(({wo,statusRaw})=>{
    const prev=byWo.get(woKey(wo));
    if(!prev||isCancelled(prev))return;
    const next={...prev,status:"complete",erpStatus:statusRaw||"מבוטלת"};
    updated.push(next);cancelled++;
    if(changes.length<400)changes.push({wo:next.woNumber,fields:["בוטלה — תוסתר"],
      from:String(prev.erpStatus||SL[prev.status||"open"]||""),to:next.erpStatus});
  });
  return{added,updated,unchanged,changes,logs,dropLogIds,newSerials,progressChanged,cancelled};
}
// ── כפילויות שכבר נוצרו ───────────────────────────────────────────────────
// Before the import learned to update in place, every "הוסף לקיימים" run added
// the whole report again — so a פק"ע that appeared in three monthly files is now
// three rows, each with its own serial numbers and its own slice of the reported
// work. Folding them back together is not a delete: the rows that go have to hand
// their units, their תקלות, their חוסרים and above all their דיווחי עבודה to the
// row that stays, or the progress leaves with them.
//
// The row that stays is the one carrying the most reported work. Serial numbers
// are matched by S/N across the duplicates, so a unit that exists twice under two
// ids becomes one unit and both rows' logs point at it.
function dupMergePlan(orders,workLogs){
  const byWo=new Map();
  (orders||[]).forEach(o=>{const k=woKey(o.woNumber);if(!k)return;const a=byWo.get(k);a?a.push(o):byWo.set(k,[o])});
  const logsByOrder=new Map();
  (workLogs||[]).forEach(w=>{if(!w.orderId)return;const a=logsByOrder.get(w.orderId);a?a.push(w):logsByOrder.set(w.orderId,[w])});
  const keepers=[],dropIds=[],movedLogs=[],dropLogIds=[],groups=[];
  byWo.forEach(rows=>{
    if(rows.length<2)return;
    const score=o=>(logsByOrder.get(o.id)||[]).length*1000+(o.serials||[]).length;
    const keep={...rows.slice().sort((a,b)=>score(b)-score(a))[0]};
    const others=rows.filter(o=>o.id!==keep.id);
    const bySn=new Map((keep.serials||[]).map(sr=>[snKey(sr.sn),sr]));
    const serials=[...(keep.serials||[])];
    const defects=[...(keep.defects||[])],shortages=[...(keep.shortages||[])];
    const delivered=new Set(keep.deliveredSerials||[]);
    // What the keeper already holds from an import, so the same stage is not
    // counted twice when the duplicate's copy of it arrives.
    const erpSeen=new Set((logsByOrder.get(keep.id)||[]).filter(w=>w.userId===PRI_LOG_USER)
      .map(w=>w.serialId?`s|${w.serialId}|${w.stageId}`:`q|${w.stageId}`));
    let addedSerials=0,moved=0,dropped=0;
    others.forEach(o=>{
      const remap=new Map();
      (o.serials||[]).forEach(sr=>{
        const hit=bySn.get(snKey(sr.sn));
        if(hit){remap.set(sr.id,hit.id);return}
        serials.push(sr);bySn.set(snKey(sr.sn),sr);addedSerials++;
      });
      (o.defects||[]).forEach(d=>{if(!defects.some(x=>x.id===d.id))defects.push(d)});
      (o.shortages||[]).forEach(x=>{if(!shortages.some(y=>y.id===x.id))shortages.push(x)});
      (o.deliveredSerials||[]).forEach(id=>delivered.add(remap.get(id)||id));
      (logsByOrder.get(o.id)||[]).forEach(w=>{
        const sid=w.serialId?(remap.get(w.serialId)||w.serialId):null;
        // The ERP's progress is a count, not an event: the same stage arriving
        // from two copies of the same פק"ע is one fact stated twice.
        if(w.userId===PRI_LOG_USER){
          const k2=sid?`s|${sid}|${w.stageId}`:`q|${w.stageId}`;
          if(erpSeen.has(k2)){dropLogIds.push(w.id);dropped++;return}
          erpSeen.add(k2);
        }
        movedLogs.push({...w,orderId:keep.id,serialId:sid});moved++;
      });
      dropIds.push(o.id);
    });
    // A duplicate that was imported later usually carries the newer status.
    const newest=rows.reduce((a,b)=>(String(b.erpStatus||"")&&!String(a.erpStatus||""))?b:a,keep);
    if(newest!==keep&&newest.erpStatus){keep.status=newest.status;keep.erpStatus=newest.erpStatus;keep.erpNote=newest.erpNote||keep.erpNote}
    keep.serials=serials;keep.defects=defects;keep.shortages=shortages;keep.deliveredSerials=[...delivered];
    keepers.push(keep);
    groups.push({wo:keep.woNumber,rows:rows.length,addedSerials,moved,dropped});
  });
  groups.sort((a,b)=>b.rows-a.rows);
  return{keepers,dropIds,movedLogs,dropLogIds,groups};
}
const XL_STAT_IN={"פתוחה":"open","פתוח":"open","open":"open","חלקית":"partial","חלקי":"partial","partial":"partial",
  "הושלמה":"complete","הושלם":"complete","סגורה":"complete","complete":"complete","תקועה":"blocked","חסומה":"blocked","blocked":"blocked"};

export {priScan,priBuild,priMergePlan,priAutoMap,priStatus,priRelog,priStamp,progPerStage,progSig,woKey,snKey,xlNorm,xlRow,PRI_H,PRI_S,PRI_NOTE_H,PRI_SKIP,PRI_NEW,PRI_LOG_USER,PRI_LOG_NAME,dbToOrder,orderToDb,dbToLog,logToDb,dbToStage,stageToDb,dbToProject,projectToDb,dbToPnStd,pnStdToDb,branchCode,isQtyLog,nowISO,uid};
